language: ruby
sudo: false
script:
  - bundle exec rspec spec
before_install:
  - gem install bundler
  - "rm ${BUNDLE_GEMFILE}.lock"
  - curl -L https://github.com/kr/beanstalkd/archive/v1.10.tar.gz | tar xz -C /tmp
  - cd /tmp/beanstalkd-1.10/
  - make
  - ./beanstalkd &
  - cd $TRAVIS_BUILD_DIR
before_script:
  - bundle update
rvm:
  - 2.2.2
  - ruby-head
